[2025-01-27T08:59:20.069+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-27T08:59:20.103+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_pollutant_averages.calculate_daily_averages scheduled__2025-01-27T08:45:00+00:00 [queued]>
[2025-01-27T08:59:20.116+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_pollutant_averages.calculate_daily_averages scheduled__2025-01-27T08:45:00+00:00 [queued]>
[2025-01-27T08:59:20.116+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-27T08:59:20.136+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): calculate_daily_averages> on 2025-01-27 08:45:00+00:00
[2025-01-27T08:59:20.149+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'daily_pollutant_averages', 'calculate_daily_averages', 'scheduled__2025-01-27T08:45:00+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/calcul_avg_polluant_by_day.py', '--cfg-path', '/tmp/tmpsu564384']
[2025-01-27T08:59:20.153+0000] {standard_task_runner.py:105} INFO - Job 57: Subtask calculate_daily_averages
[2025-01-27T08:59:20.153+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=956) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-27T08:59:20.154+0000] {standard_task_runner.py:72} INFO - Started process 959 to run task
[2025-01-27T08:59:20.232+0000] {task_command.py:467} INFO - Running <TaskInstance: daily_pollutant_averages.calculate_daily_averages scheduled__2025-01-27T08:45:00+00:00 [running]> on host 9f988a59261a
[2025-01-27T08:59:20.364+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_pollutant_averages' AIRFLOW_CTX_TASK_ID='calculate_daily_averages' AIRFLOW_CTX_EXECUTION_DATE='2025-01-27T08:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-27T08:45:00+00:00'
[2025-01-27T08:59:20.366+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-27T08:59:20.401+0000] {logging_mixin.py:190} INFO - Traitement des donn√©es pour la station 283164601...
[2025-01-27T08:59:20.454+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/calcul_avg_polluant_by_day.py", line 82, in run_daily_averages
    calculate_daily_averages()
  File "/opt/airflow/dags/calcul_avg_polluant_by_day.py", line 55, in calculate_daily_averages
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2025-01-27T08:59:20.467+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=daily_pollutant_averages, task_id=calculate_daily_averages, run_id=scheduled__2025-01-27T08:45:00+00:00, execution_date=20250127T084500, start_date=20250127T085920, end_date=20250127T085920
[2025-01-27T08:59:20.495+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-27T08:59:20.496+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 57 for task calculate_daily_averages (type object 'datetime.datetime' has no attribute 'datetime'; 959)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/calcul_avg_polluant_by_day.py", line 82, in run_daily_averages
    calculate_daily_averages()
  File "/opt/airflow/dags/calcul_avg_polluant_by_day.py", line 55, in calculate_daily_averages
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                ^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
[2025-01-27T08:59:20.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-27T08:59:20.576+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-27T08:59:20.580+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
