[2025-01-25T08:10:34.251+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T08:10:34.300+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T08:00:00+00:00 [queued]>
[2025-01-25T08:10:34.324+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T08:00:00+00:00 [queued]>
[2025-01-25T08:10:34.325+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T08:10:34.374+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-01-25 08:00:00+00:00
[2025-01-25T08:10:34.392+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_2', 'scheduled__2025-01-25T08:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp5a163n54']
[2025-01-25T08:10:34.398+0000] {standard_task_runner.py:105} INFO - Job 32: Subtask extract_and_load_to_mongodb_station_2
[2025-01-25T08:10:34.399+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=12484) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T08:10:34.400+0000] {standard_task_runner.py:72} INFO - Started process 12493 to run task
[2025-01-25T08:10:34.493+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T08:00:00+00:00 [running]> on host 8969ebd0a926
[2025-01-25T08:10:34.671+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T08:00:00+00:00'
[2025-01-25T08:10:34.673+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T08:10:34.859+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe6398820c0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -2] Name or service not known)"))
[2025-01-25T08:10:34.868+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe6398e82f0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -2] Name or service not known)"))
[2025-01-25T08:10:34.869+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283181971.
[2025-01-25T08:10:34.869+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T08:10:34.904+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T08:10:34.905+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_2, run_id=scheduled__2025-01-25T08:00:00+00:00, execution_date=20250125T080000, start_date=20250125T081034, end_date=20250125T081034
[2025-01-25T08:10:34.943+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T08:10:34.964+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
