[2025-01-25T18:10:06.392+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T18:10:06.463+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T15:35:00+00:00 [queued]>
[2025-01-25T18:10:06.498+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T15:35:00+00:00 [queued]>
[2025-01-25T18:10:06.508+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T18:10:06.563+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-01-25 15:35:00+00:00
[2025-01-25T18:10:06.596+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_2', 'scheduled__2025-01-25T15:35:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpj24fw0ip']
[2025-01-25T18:10:06.613+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=4924) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T18:10:06.614+0000] {standard_task_runner.py:72} INFO - Started process 4931 to run task
[2025-01-25T18:10:06.614+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask extract_and_load_to_mongodb_station_2
[2025-01-25T18:10:06.966+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T15:35:00+00:00 [running]> on host 64d28392d4c0
[2025-01-25T18:10:07.619+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T15:35:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T15:35:00+00:00'
[2025-01-25T18:10:07.626+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T18:10:15.782+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bc6fcb0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T18:10:23.792+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bcd4260>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T18:10:23.800+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283181971.
[2025-01-25T18:10:23.800+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T18:10:24.039+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T18:10:24.040+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_2, run_id=scheduled__2025-01-25T15:35:00+00:00, execution_date=20250125T153500, start_date=20250125T181006, end_date=20250125T181024
[2025-01-25T18:10:24.100+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T18:10:24.122+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-25T18:10:24.126+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
