[2025-01-25T19:27:37.865+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T19:27:37.918+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [queued]>
[2025-01-25T19:27:37.942+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [queued]>
[2025-01-25T19:27:37.943+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T19:27:37.945+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-25T19:27:37.984+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [queued]>
[2025-01-25T19:27:37.988+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-01-25 19:20:00+00:00
[2025-01-25T19:27:38.011+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [queued]>
[2025-01-25T19:27:38.011+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-25T19:27:38.016+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_2', 'scheduled__2025-01-25T19:20:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp1081qzg3']
[2025-01-25T19:27:38.031+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask extract_and_load_to_mongodb_station_2
[2025-01-25T19:27:38.036+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T19:27:38.039+0000] {standard_task_runner.py:72} INFO - Started process 6488 to run task
[2025-01-25T19:27:38.077+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_2> on 2025-01-25 19:20:00+00:00
[2025-01-25T19:27:38.094+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v11', 'extract_and_load_to_mongodb_station_2', 'scheduled__2025-01-25T19:20:00+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpnbs7gx2m']
[2025-01-25T19:27:38.103+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=19814) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-25T19:27:38.104+0000] {standard_task_runner.py:105} INFO - Job 41: Subtask extract_and_load_to_mongodb_station_2
[2025-01-25T19:27:38.104+0000] {standard_task_runner.py:72} INFO - Started process 19816 to run task
[2025-01-25T19:27:38.167+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [running]> on host 64d28392d4c0
[2025-01-25T19:27:38.266+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v11.extract_and_load_to_mongodb_station_2 scheduled__2025-01-25T19:20:00+00:00 [running]> on host 8969ebd0a926
[2025-01-25T19:27:38.545+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T19:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T19:20:00+00:00'
[2025-01-25T19:27:38.548+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T19:27:38.742+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v11' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_2' AIRFLOW_CTX_EXECUTION_DATE='2025-01-25T19:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-25T19:20:00+00:00'
[2025-01-25T19:27:38.752+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-25T19:27:38.937+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe6399b4bc0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -2] Name or service not known)"))
[2025-01-25T19:27:38.944+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fe6398ec380>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -2] Name or service not known)"))
[2025-01-25T19:27:38.945+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283181971.
[2025-01-25T19:27:38.946+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T19:27:38.999+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T19:27:39.000+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_2, run_id=scheduled__2025-01-25T19:20:00+00:00, execution_date=20250125T192000, start_date=20250125T192737, end_date=20250125T192738
[2025-01-25T19:27:39.067+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T19:27:39.082+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-01-25T19:27:46.669+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bd748f0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T19:27:54.679+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc68bcd8530>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-01-25T19:27:54.685+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283181971.
[2025-01-25T19:27:54.686+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-25T19:27:55.310+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-25T19:27:55.311+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v11, task_id=extract_and_load_to_mongodb_station_2, run_id=scheduled__2025-01-25T19:20:00+00:00, execution_date=20250125T192000, start_date=20250125T192737, end_date=20250125T192755
[2025-01-25T19:27:55.359+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-25T19:27:55.366+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
