[2025-02-02T07:50:11.528+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T07:50:11.549+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecasting_hourly.run_forecasting scheduled__2025-02-02T06:00:00+00:00 [queued]>
[2025-02-02T07:50:11.557+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecasting_hourly.run_forecasting scheduled__2025-02-02T06:00:00+00:00 [queued]>
[2025-02-02T07:50:11.557+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T07:50:11.570+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_forecasting> on 2025-02-02 06:00:00+00:00
[2025-02-02T07:50:11.578+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecasting_hourly', 'run_forecasting', 'scheduled__2025-02-02T06:00:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/forecasting_by_hour.py', '--cfg-path', '/tmp/tmpedeaw58v']
[2025-02-02T07:50:11.582+0000] {standard_task_runner.py:105} INFO - Job 95: Subtask run_forecasting
[2025-02-02T07:50:11.582+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=70757) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T07:50:11.583+0000] {standard_task_runner.py:72} INFO - Started process 70758 to run task
[2025-02-02T07:50:11.626+0000] {task_command.py:467} INFO - Running <TaskInstance: forecasting_hourly.run_forecasting scheduled__2025-02-02T06:00:00+00:00 [running]> on host 6f5fd3382d74
[2025-02-02T07:50:11.704+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecasting_hourly' AIRFLOW_CTX_TASK_ID='run_forecasting' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T06:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T06:00:00+00:00'
[2025-02-02T07:50:11.705+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T07:50:11.787+0000] {logging_mixin.py:190} INFO - Erreur lors de l'exécution du script de prévision : Command '['python3', '/ml/forecasting.py']' returned non-zero exit status 2.
[2025-02-02T07:50:11.788+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T07:50:11.797+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T07:50:11.797+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecasting_hourly, task_id=run_forecasting, run_id=scheduled__2025-02-02T06:00:00+00:00, execution_date=20250202T060000, start_date=20250202T075011, end_date=20250202T075011
[2025-02-02T07:50:11.838+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T07:50:11.852+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T07:50:11.853+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
