[2025-01-24T20:04:22.844+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T20:04:22.861+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v10.extract_and_load_to_mongodb_station_1 manual__2025-01-24T20:04:22.363698+00:00 [queued]>
[2025-01-24T20:04:22.871+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v10.extract_and_load_to_mongodb_station_1 manual__2025-01-24T20:04:22.363698+00:00 [queued]>
[2025-01-24T20:04:22.871+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T20:04:22.887+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-24 20:04:22.363698+00:00
[2025-01-24T20:04:22.898+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=5096) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-24T20:04:22.899+0000] {standard_task_runner.py:72} INFO - Started process 5097 to run task
[2025-01-24T20:04:22.900+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v10', 'extract_and_load_to_mongodb_station_1', 'manual__2025-01-24T20:04:22.363698+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpmx_cfs3l']
[2025-01-24T20:04:22.903+0000] {standard_task_runner.py:105} INFO - Job 14: Subtask extract_and_load_to_mongodb_station_1
[2025-01-24T20:04:22.945+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v10.extract_and_load_to_mongodb_station_1 manual__2025-01-24T20:04:22.363698+00:00 [running]> on host 8969ebd0a926
[2025-01-24T20:04:23.020+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v10' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-24T20:04:22.363698+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-24T20:04:22.363698+00:00'
[2025-01-24T20:04:23.020+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T20:05:20.395+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 6793f26339f071e8fbd6341a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 20000.0ms, connectTimeoutMS: 20000.0ms)')>]>
[2025-01-24T20:05:20.403+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-24T20:05:20.586+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T20:05:20.587+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v10, task_id=extract_and_load_to_mongodb_station_1, run_id=manual__2025-01-24T20:04:22.363698+00:00, execution_date=20250124T200422, start_date=20250124T200422, end_date=20250124T200520
[2025-01-24T20:05:20.637+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-24T20:05:20.652+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T20:05:20.654+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
