[2025-02-02T08:01:49.520+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T08:01:49.539+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecasting_by_hour_v2.run_forecasting manual__2025-02-02T08:01:48.751490+00:00 [queued]>
[2025-02-02T08:01:49.547+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecasting_by_hour_v2.run_forecasting manual__2025-02-02T08:01:48.751490+00:00 [queued]>
[2025-02-02T08:01:49.547+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T08:01:49.560+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_forecasting> on 2025-02-02 08:01:48.751490+00:00
[2025-02-02T08:01:49.567+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecasting_by_hour_v2', 'run_forecasting', 'manual__2025-02-02T08:01:48.751490+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/forecasting_by_hour.py', '--cfg-path', '/tmp/tmp59kdp3rl']
[2025-02-02T08:01:49.570+0000] {standard_task_runner.py:105} INFO - Job 103: Subtask run_forecasting
[2025-02-02T08:01:49.574+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=71309) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T08:01:49.574+0000] {standard_task_runner.py:72} INFO - Started process 71310 to run task
[2025-02-02T08:01:49.608+0000] {task_command.py:467} INFO - Running <TaskInstance: forecasting_by_hour_v2.run_forecasting manual__2025-02-02T08:01:48.751490+00:00 [running]> on host 6f5fd3382d74
[2025-02-02T08:01:49.686+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecasting_by_hour_v2' AIRFLOW_CTX_TASK_ID='run_forecasting' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T08:01:48.751490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T08:01:48.751490+00:00'
[2025-02-02T08:01:49.686+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T08:01:49.724+0000] {logging_mixin.py:190} INFO - Erreur lors de l'exécution du script de prévision : Command '['python3', '../ml/forecasting.py']' returned non-zero exit status 2.
[2025-02-02T08:01:49.725+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T08:01:49.733+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T08:01:49.733+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecasting_by_hour_v2, task_id=run_forecasting, run_id=manual__2025-02-02T08:01:48.751490+00:00, execution_date=20250202T080148, start_date=20250202T080149, end_date=20250202T080149
[2025-02-02T08:01:49.749+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T08:01:49.762+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T08:01:49.764+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
