[2025-01-26T00:39:31.678+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T00:39:31.707+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v12.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:39:31.012103+00:00 [queued]>
[2025-01-26T00:39:31.721+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v12.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:39:31.012103+00:00 [queued]>
[2025-01-26T00:39:31.721+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T00:39:31.741+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-01-26 00:39:31.012103+00:00
[2025-01-26T00:39:31.758+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=290) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-01-26T00:39:31.754+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v12', 'extract_and_load_to_mongodb_station_1', 'manual__2025-01-26T00:39:31.012103+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmpmwm_s7tx']
[2025-01-26T00:39:31.759+0000] {standard_task_runner.py:72} INFO - Started process 293 to run task
[2025-01-26T00:39:31.759+0000] {standard_task_runner.py:105} INFO - Job 38: Subtask extract_and_load_to_mongodb_station_1
[2025-01-26T00:39:31.825+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v12.extract_and_load_to_mongodb_station_1 manual__2025-01-26T00:39:31.012103+00:00 [running]> on host 63b35b4cd871
[2025-01-26T00:39:31.947+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v12' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T00:39:31.012103+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T00:39:31.012103+00:00'
[2025-01-26T00:39:31.948+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T00:40:14.145+0000] {logging_mixin.py:190} INFO - Erreur lors de l'insertion dans MongoDB : localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms), Timeout: 30s, Topology Description: <TopologyDescription id: 679584516196cfff9f021508, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [Errno 111] Connection refused (configured timeouts: socketTimeoutMS: 60000.0ms, connectTimeoutMS: 60000.0ms)')>]>
[2025-01-26T00:40:14.157+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-26T00:40:14.383+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T00:40:14.384+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v12, task_id=extract_and_load_to_mongodb_station_1, run_id=manual__2025-01-26T00:39:31.012103+00:00, execution_date=20250126T003931, start_date=20250126T003931, end_date=20250126T004014
[2025-01-26T00:40:14.440+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T00:40:14.459+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T00:40:14.462+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
