[2025-02-02T09:00:00.479+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T09:00:00.501+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forecasting_by_hour_v2.run_forecasting scheduled__2025-02-02T08:00:00+00:00 [queued]>
[2025-02-02T09:00:00.508+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forecasting_by_hour_v2.run_forecasting scheduled__2025-02-02T08:00:00+00:00 [queued]>
[2025-02-02T09:00:00.509+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T09:00:00.520+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): run_forecasting> on 2025-02-02 08:00:00+00:00
[2025-02-02T09:00:00.527+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'forecasting_by_hour_v2', 'run_forecasting', 'scheduled__2025-02-02T08:00:00+00:00', '--job-id', '104', '--raw', '--subdir', 'DAGS_FOLDER/forecasting_by_hour.py', '--cfg-path', '/tmp/tmpkud1yp11']
[2025-02-02T09:00:00.529+0000] {standard_task_runner.py:105} INFO - Job 104: Subtask run_forecasting
[2025-02-02T09:00:00.535+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=73824) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T09:00:00.535+0000] {standard_task_runner.py:72} INFO - Started process 73825 to run task
[2025-02-02T09:00:00.564+0000] {task_command.py:467} INFO - Running <TaskInstance: forecasting_by_hour_v2.run_forecasting scheduled__2025-02-02T08:00:00+00:00 [running]> on host 6f5fd3382d74
[2025-02-02T09:00:00.648+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='forecasting_by_hour_v2' AIRFLOW_CTX_TASK_ID='run_forecasting' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T08:00:00+00:00'
[2025-02-02T09:00:00.649+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T09:00:00.737+0000] {logging_mixin.py:190} INFO - Erreur lors de l'exécution du script de prévision : Command '['python3', '../ml/forecasting.py']' returned non-zero exit status 2.
[2025-02-02T09:00:00.737+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T09:00:00.745+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T09:00:00.745+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forecasting_by_hour_v2, task_id=run_forecasting, run_id=scheduled__2025-02-02T08:00:00+00:00, execution_date=20250202T080000, start_date=20250202T090000, end_date=20250202T090000
[2025-02-02T09:00:00.790+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T09:00:00.797+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
