[2025-02-02T12:00:01.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T12:00:01.457+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T11:00:00+00:00 [queued]>
[2025-02-02T12:00:01.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T11:00:00+00:00 [queued]>
[2025-02-02T12:00:01.464+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-02T12:00:01.475+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): extract_and_load_to_mongodb_station_1> on 2025-02-02 11:00:00+00:00
[2025-02-02T12:00:01.484+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'extraction_by_hour_dag_v15', 'extract_and_load_to_mongodb_station_1', 'scheduled__2025-02-02T11:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_by_hour.py', '--cfg-path', '/tmp/tmp33r9ck_n']
[2025-02-02T12:00:01.487+0000] {standard_task_runner.py:105} INFO - Job 114: Subtask extract_and_load_to_mongodb_station_1
[2025-02-02T12:00:01.498+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=81622) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-02T12:00:01.498+0000] {standard_task_runner.py:72} INFO - Started process 81627 to run task
[2025-02-02T12:00:01.529+0000] {task_command.py:467} INFO - Running <TaskInstance: extraction_by_hour_dag_v15.extract_and_load_to_mongodb_station_1 scheduled__2025-02-02T11:00:00+00:00 [running]> on host 6f5fd3382d74
[2025-02-02T12:00:01.596+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='extraction_by_hour_dag_v15' AIRFLOW_CTX_TASK_ID='extract_and_load_to_mongodb_station_1' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-02T11:00:00+00:00'
[2025-02-02T12:00:01.597+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T12:00:17.713+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283164601 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283164601 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb2a162b260>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-02-02T12:00:33.723+0000] {logging_mixin.py:190} INFO - Erreur pour la station 283181971 : HTTPSConnectionPool(host='airqino-api.magentalab.it', port=443): Max retries exceeded with url: /v3/getStationHourlyAvg/283181971 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fb2a14dccb0>: Failed to resolve 'airqino-api.magentalab.it' ([Errno -3] Temporary failure in name resolution)"))
[2025-02-02T12:00:33.728+0000] {logging_mixin.py:190} INFO - Aucune donnée valide récupérée pour la station 283164601.
[2025-02-02T12:00:33.728+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T12:00:33.737+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T12:00:33.738+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=extraction_by_hour_dag_v15, task_id=extract_and_load_to_mongodb_station_1, run_id=scheduled__2025-02-02T11:00:00+00:00, execution_date=20250202T110000, start_date=20250202T120001, end_date=20250202T120033
[2025-02-02T12:00:33.931+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-02T12:00:33.943+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-02T12:00:33.944+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
